### ISSUE TITLE
Branch/Merge in Magic Draw

### ISSUE THREAD

**Issue by brittanyfriedland** [Open-MBEE/mdk#13]
I have followed the instructions in the MagicDraw MDK Manual section 3.5 and I cannot get branching/merging to work within magic draw. The instructions mention how to create a branch using magic draw's teamwork server but don't mention anything about how to do it within alfresco and how to align the two if you don't have teamwork server. Do you need to have teamwork server or can you create branches/merge with using magic draw, alfresco and the open mbee plug ins?

**Comment by cinyoung** [comment]
From MMS menu select Check Modules and Branches. The validation window shows any modules or branches that are missing from the server. The branch fix will automatically create the appropriate branch on MMS. Branch on teamwork and MMS must have the exact same name.

Any missing modules will also be displayed. You'll need to upload these first before uploading your project. This consists of creating the site, then rerunning the check, then posting the module data to MMS.

If you don't have a teamwork server, you can still branch on MMS, but you can only sync to master branch from MD. To see the branching options in the GUIs, by default you need to be an administrator (we're changing this so everyone can see it in the future - or a specific Alfresco group).
