### ISSUE TITLE
MDK doesn't report offending elements on commit

### ISSUE THREAD

**Issue by wobrschalek** [Open-MBEE/mdk#243]
When there are certain types of hidden elements at package level (e.g. value specifications, literal strings), a commit of the whole model
is aborted but not reported back to CSM.
The only way to debug the model is to inspect the backend to find the offending IDs since they cannot be found through the CSM UI.
MMS reports back in the response the offending elements but they are not logged.

possible solutions
* log response from MMS in .log file - could be an option to be turned on in project options
* the validate function flags those hidden elements

**Comment by dlamoris** [comment]
i want to try and test this but md won't even allow me to create a value spec inside a package, not sure how i can recreate the conditions to get the error

**Comment by dlamoris** [comment]
there is an option under Options > Environment > MDK to Log JSON, it may be broken right now but will be fixed
