### ISSUE TITLE
Multibyte characters are removed

### ISSUE THREAD

**Issue by crimson707** [Open-MBEE/mdk#249]
The process of synchronizing with mms removes multibyte characters from mms.
I think it might be due to the replace processing of the fixString function in DocGenUtils.java.

https://github.com/Open-MBEE/mdk/blob/develop/src/main/java/gov/nasa/jpl/mbee/mdk/docgen/DocGenUtils.java#L178

**Comment by dlamoris** [comment]
when you say synchronizing, did you mean just the pushing of a project to mms causes those characters to not be on mms, or is it limited to use cases involving ve/view generation?

**Comment by crimson707** [comment]
As far as I know, it occurs only in the latter case. When I tried to use multibyte characters as a column name in the TableStructure, they were not printed in mms after the ve/view generation process.

**Comment by crimson707** [comment]
Thanks for your response.
