### ISSUE TITLE
Trying to Create Custom Jython

### ISSUE THREAD

**Issue by jbpinch** [Open-MBEE/mdk#26]
Hello,

I'm trying to utilize the UserScript component of DocGen, so I've created a stereotype that extends UserScript, and a .py file by the same name as my stereotype to compile when the document is generated. I've been able to run scripts, so I know my python script is set up appropriately. However, it seems like in order to write to the DocGen report, the script requires the function DBParagraph, which is located in gov.nasa.jpl.mgss.docgen.docbook. Is this package available so we can run UserScripts?

Thanks.

**Comment by dlamoris** [comment]
if you're using the zip uploaded in the past month, go into plugins/gov.nasa.jpl.mbee.docgen/ and set the ownClassloader attribute in plugin.xml to false instead of true. this should restore the use of userscripts, but may generate errors when using ocl

**Comment by dlamoris** [comment]
to use both, you'll need to replace the ocl libs in magicdraw's lib folder with the ones from this repo, and edit bin/magicdraw.properties's classpath to include the updated libs accordingly.

**Comment by jbpinch** [comment]
Unfortunately, the first step you suggested did not work. The second step crashed my MagicDraw, so I reinstalled, at which point I couldn't even get scripts to run at all through MagicDraw now. There are 7 ocl jar files in the CSM 18.1 lib, and there are 4 in your repo. Are you suggesting that I delete all 7 of CSM's ocl jars now and replace them with just the 4 in your repo? Is there another way I can get DBParagraph?

**Comment by dlamoris** [comment]
try just taking out any ocl reference in our plugin.xml (so you won't be able to use ocl for docgen) and make ownClassloader false. (the second step was assuming you're using md 18.0, the replacement jars just replace their corresponding jar in md's lib, not all of them)

**Comment by jbpinch** [comment]
I've made these changes and DocGen is working with its internal commands (like it has all along), but I still can't generate from my Python script. Plus, I'm one step back from where I was at the beginning because at that point, I could establish a connection between a stereotyped action and its corresponding Python script. I can no longer establish that connection, let alone generate text from my Python code.

**Comment by dlamoris** [comment]
can you check the import is gov.nasa.jpl.mgss.mbee.docgen.docbook (your first comment is missing mbee)
just tested the following on magicdraw 18.0 sp4 and should work:
put ownClassloader as false and comment out ocl lib imports in plugin.xml

**Comment by jbpinch** [comment]
So here are the steps I've tried on both Cameo Systems Modeler 18.0 SP2 and Cameo Systems Modeler 18.1:
1. Download the zip file docgen-18.0.zip.
2. In CSM, under Resource/Plugin Manager, click Import to import docgen-18.0.zip. Restart CSM.
3. In <CSM root>/plugins/gov.nasa.jpl.mbee.docgen/plugin.xml, change ownClassloader to false. When this doesn't work, go back in and comment out ocl lib imports.
4. In the model, create a stereotype <<Test.MakeParagraph>> that extends UserScript. The reason I chose this is because there is already a MakeParagraph.py test script in <CSM root>/DocGenUserScripts/Test that is supposed to print "Hello World".
5. Create a document, view, and viewpoint. The for the viewpoint method diagram attached to the viewpoint, create an "other" activity and apply the <<Test.MakeParagraph>> stereotype. Give it a beginning and ending node.
6. From the document element, generate the report. I assume at this point, "Hello World" is supposed to be written to my script. It isn't.
7. I tried changing the working directory to my Python script, but that didn't fix the problem either.

I'm not sure if this is the problem of finding the DBParagraph (which is located, according to MakeParagraph.py, in gov.nasa.jpl.mgss.mbee.docgen.docbook, as you said), if I am expecting the wrong output, or if something else is going on here. Also, I was originally able to run scripts from MakeParagraph.py, such as generating pop-up windows, so I knew DocGen was at least reading my scripts, but now I can't even duplicate that, so I'm not even sure DocGen is still reading the scripts. Either way, I have not yet had success using Python UserScripts to write to my xml documents and am hoping this list of steps I took will help identify why that isn't happening.

**Comment by dlamoris** [comment]
can you attach screenshots showing your activity model and custom stereotype hookups, your steps all look right, the only thing i can think of is maybe a typo in your stereotype (name should be "Test.MakeParagraph"), or there's some differences between plain magicdraw and csm (docgen hasn't been tested on csm variant), but you mentioned you've been able to run from it before, so that's unlikely

**Comment by jbpinch** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/5487513/11043076/c5b17a30-86cf-11e5-8b21-7aeb09c825f8.png)
![screenshot2](https://cloud.githubusercontent.com/assets/5487513/11043215/803feaf8-86d0-11e5-95c4-fcba1f5522ff.png)

The first screenshot shows my View Diagram. The second screenshot shows the Viewpoint Method Diagram for my second viewpoint, Bulk Document Viewpoint. The second screenshot also shows part of the specification for the Test.MakeParagraph stereotype.

The first time I was able to get a connection between CSM and DocGen userscripts was when I was using a version of DocGen that a colleague had packaged to better interact with our version of CSM. The second time, when I was not able to establish that connection, was when I was using the DocGen zip file from your site that was uploaded a few weeks back. Therefore, I wouldn't be surprised if the issue is the packaging for CSM vs. MagicDraw.

**Comment by dlamoris** [comment]
turns out the MakeParagraph example is slightly wrong, you'll need to put 
scriptOutput = {'DocGenOutput': [DBParagraph("hello world")]}
the DocGenTest.py has a better example (comment out references to sproperty)

**Comment by jbpinch** [comment]
That did it! Thank you so much for all of the assistance.

**Comment by jbpinch** [comment]
So I have been able to link my model and DocGen to my python scripts, but is there any additional documentation on the UserScripts other than the last few pages of the user manual? I am having luck with the directives getName() and getOwner(), but I am not having luck getting element type (such as block, use case, etc.) or with getStereotype(). Additionally, I am not having luck with the Collect/Filter UserScript example in 3.8.2 of the manual. If there are other locations where I can look for resolutions, or additional capabilities and directives for the UserScripts, I would love to be pointed in those directions. Thanks!

**Comment by dlamoris** [comment]
the elements being passed in are magicdraw's java api elements, so you can use md's openapi/javadoc for available methods

**Comment by jbpinch** [comment]
I assumed that was the case, but using elt.getName() and using the api made me think that elt.getDocumentation() would work as well. Unfortunately, it does not. Maybe I am using api incorrectly; otherwise, please let me know how I can resolve this. Thanks.

**Comment by dlamoris** [comment]
for documentation, use com.nomagic.uml2.ext.jmi.helpers.ModelHelper.getComment(element), for working with stereotypes and tagged values, use com.nomagic.uml2.ext.jmi.helpers.StereotypesHelper

**Comment by jbpinch** [comment]
Thanks, this has been so helpful. I noticed in your DocGen manual that the only way to expose a diagram is to use a special diagram view. This brings up a few questions:

1. I have a package containing many use cases, each of which contains an interaction, and then each of which contains a diagram. If I want to display all of those diagrams, do I have to manually expose each diagram, each with its own diagram view?
2. If I want to display the use case documentation before each diagram, is there a way to intersperse the view from the use case's documentation with the view from the diagram, or does the view exposing the use case documentation have to come wholly before the diagram view?
3. If I decide to do this with UserScripts, I believe the proper call to display a diagram is diagram.getDiagramPresentationElement. Do I feed this into the output array? If so, does it then get fed into DBParagraph, or is there another way to display it?

Thanks,
Julie

**Comment by dlamoris** [comment]
the diagram view is only a shortcut (if a view exposes a diagram and have no viewpoint, it'll print the diagram)
with a viewpoint, you can expose the package with the use cases, and do something like the following:
1. collect and filter the use cases
2. make a structured query that loops through the use cases, inside the structured query, use a paragraph action to print the use case documentation, then collect and filter your way to the use case diagram, use diagram action to print the diagram (with loop, the 'context' for the structure query would be a single use case)

**Comment by dlamoris** [comment]
in script, there's also a DBImage that takes a md diagram object
https://github.com/Open-MBEE/MDK/blob/2.2/src/main/java/gov/nasa/jpl/mgss/mbee/docgen/docbook/DBImage.java

**Comment by jbpinch** [comment]
Thanks. When I do output.append(DBImage(dia)), the diagram is printed twice, once as an SVG, and once as a PNG. The same thing happens when I expose the diagram using an <<Image>> action on a viewpoint diagram. Is there a way to prevent both from being printed?

Slightly unrelated, in my document block, I removed JPL's name as well is its distribution statements from the legal notices and other attributes, but that information still shows up on my document. Is it stored in an xml file somewhere where I can remove that information?

Thanks.

**Comment by jbpinch** [comment]
One other question in the meantime...I am trying to use a Python package docx in my user script. Where would be the proper place to store this package so the DocGen UserScript can find it?

Thanks,

Julie

**Comment by dlamoris** [comment]
for image being printed twice, it's not really twice since one is for html and one is for pdf transform, so if you use oxygen or docbook stylesheets it should use only one of them

the legal info can be deleted from the generated docbook xml file, it should be near the top, (it may be using the default values in the profile if they're not filled in, so you can also delete them from the stereotype in the profile)

you may be able to drop the package as a module either in the same directory as the userscript, at the DocGenUserscript directory, or in the python modules directory under plugins/com.nomagic.magicdraw.jpython/jython/Lib
