### ISSUE TITLE
Is there any way to sort prefixed and multi-leveled IDs?

### ISSUE THREAD

**Issue by CampusClub** [Open-MBEE/mdk#263]
Hello! I am using the SortByProperty Function and the chosen property is the ID of a requirement, as is shown in sceenshot 1.
![screenshot 1](https://github.com/Open-MBEE/mdk/assets/50562219/6225faa8-88d9-4e24-97fa-cf022cab86f5)
But the ID is prefixed and chaptered into multiple levels, as is shown in screenshot 2.
![screenshot 2](https://github.com/Open-MBEE/mdk/assets/50562219/0a4d64b0-ba5f-4b94-b3a8-362acdd4bed2)
Then as a result, the tool could not sort the IDs correctly. For example, it comes to 1.1.2 after 1.1.19, then 1.1.20, 1.1.21, etc, as is shown in screenshot 3.
![screenshot 3](https://github.com/Open-MBEE/mdk/assets/50562219/0b85410a-e275-4300-8f96-da346aeb91de)
If I change the numbering schema to consecutive, it will work. But due to application requirement, a multi-level numbering schema is more friendly to user, which is highly suggested.
So is there any way that the CDK could sort the multi-level numbering schema correctly?

**Comment by dlamoris** [comment]
sort by property will only sort by alphanumeric, so it won't understand multilevel, you may try to sort by some other property if you have something that's in the order you want, or use sortByExpression to try and use ocl (but i'm not an ocl expert so i'm afraid there's not much help i can provide there)

**Comment by CampusClub** [comment]
OK I got it. Thanks for your kind help Moris!
