### ISSUE TITLE
MDK Viewpoint TablePropertyColumn cannot find basic UML Profile Properties

### ISSUE THREAD

**Issue by gt831c** [Open-MBEE/mdk#28]
When I'm creating my view point and using TablePropertyColumns I'm having a tough time being able to point to the most basic UML Profile stuff such as "Owner" for blocks, or "Source" and "Target" for Dependencies, and I think it's because when I'm searching under DesiredProperty, I'm looking all over but I just cannot find the base UML Profile to say, "hey, I want to select the owner".

Do you have any hints like we don't have the UML Profile loaded to our project or it's not viewable?? Or why I cannot point to such properties to display when I generate my document?

**Comment by dlamoris** [comment]
TablePropertyColumn is intended for getting the property value of classifiers or slot values of stereotype tags, not uml profile properties. To show things like owner, you can use the structured activity version of TableAttributeColumn and do more collect/filtering inside the column to get the element you want (this will be applied to the element for each row in the table), then use Name as the attribute to display.
