### ISSUE TITLE
Magic Draw Table Content Not Showing in MMS?

### ISSUE THREAD

**Issue by gt831c** [Open-MBEE/mdk#29]
In Magic we are creating a bunch of tables (Right Click > Create Diagram > Other Diagrams > Generic Tables).  

We are populating tables of say Dependencies and displaying some other properties.  
When we commit them to MMS, I guess our Admin person can see the table object but not the contents of the table?  Does this sound correct?   

Do you have any tips on how to push all those Magic Draw generated tables into MMS?  Or do we have to recreate them via MDK Document Table Queries and Push to MMS that way?

**Comment by dlamoris** [comment]
There's a stereotype called GenericTable you can put on a viewpoint action and give it the md generic table as input and see if that works, although it hasn't been updated in some time
