### ISSUE TITLE
How to install MDK?

### ISSUE THREAD

**Issue by danyeaw** [Open-MBEE/mdk#33]
I'm trying to install the MDK to look at the TMT example. The README provides almost no information, and I don't see any information in the Open-MBEE wiki. Do I have to build something, or can I just install the plugin without building it? Are there libraries to replace in the lib directory in MagicDraw? I have MagicDraw 18.0 LTR installed with CST 18.4 SP1.

Should I be using master or release 3.0.0?
I tried to build the master branch using Eclipse and the build-nojenkins.xml file with Ant and I got about 100 errors.

What are the prerequisites to setup the build environment if it has to be built?

**Comment by ivan-gomes** [comment]
If your goal is to just install MDK in MagicDraw, then I would recommend using a pre-compiled plugin. You can find them in https://github.com/Open-MBEE/mvn-repo as mdk-*.*.*.zip. The currently published version is compatible with MagicDraw 18.0. 

If you would still rather compile from source we can document the steps. It involves using SBT: http://www.scala-sbt.org/

**Comment by danyeaw** [comment]
Great news that there is a pre-compiled plugin available. However, I'm having issues getting it to work.
Fresh install of MagicDraw 18.0 SP6 with CST and SysML plugins. I downloaded the mdk-2.3.3.zip file, started MagicDraw with admin privs, went to Help-> Resource / Plugin Manager. I then clicked import, selected the zip file, and nothing happens. There are no error messages and there is no message that the plugin was installed.

**Comment by danyeaw** [comment]
Version 2.4.5 of MDK loaded fine. Version 2.3.3 and 3.0.0 RC2 do not install for me. The TMT model still fails to load with version 2.4.5 of MDK, along with MagicDraw 18.0 SP6 and CST 18.4 SP1. I am getting a com.nomagic.magicdraw.persistence.xmi.load.model.utils.b failed to load error.
