### ISSUE TITLE
How does one connect the MagicDraw plugin to self-hosted OpenMBEE

### ISSUE THREAD

**Issue by phx-jrs** [Open-MBEE/mdk#5]
I am in the process of setting up my own installation of OpenMBEE.  I installed Alfresco (v4.2.f) and the OpenMBEE AMPs.  As a first smoke test of the server, I went to the Alfresco login page and I now see the Europa EMS login prompt.  

I then installed the MagicDraw plugin in MagicDraw 17.0.5.  After restarting MagicDraw, I can see the MDK and MMS menus.  When I open a project and attempt to connect to my installation of OpenMBEE the MagicDraw plugin only prompts me for my username and password.  I do not see where I need to enter the ip address/hostname of my local installation of OpenMBEE.

Is there a configuration file or setting dialog I can access to update the MMS server ip address/hostname?

Thanks!

**Comment by cukii** [comment]
@phx-jrs Were you able to get it working? I'm stuck at "Initialize project and model". I'm guessing that I am successfully logging into the server if I'm getting that message. But, all I get if I try to initialize is "The thing you're trying to validate or get wasn't found on the server, see validation window". I'm working off the alfresco amp from mvn-amp, and I created a site called "test". I'm pointing the url to "http://localhost:8080/alfresco". The Notification Window says it's "[INFO] Sending..."

**Comment by dlamoris** [comment]
@cukli just use http://localhost:8080 without the trailing alfesco as the url

**Comment by cukii** [comment]
@dlamoris Hmm, that still doesn't work. The error message I get in the validation suite says, "This project doesn't exist on the web yet, or the site has been moved." I tried different combinations of localhost, 127.0.0.1, alfresco.
