### ISSUE TITLE
Won't open under windows

### ISSUE THREAD

**Issue by RCarvalhoNASA** [Open-MBEE/mdk#6]
I am attempting to install this plugin and it is failing.  The error it gives me is:
the following resources are not suitable for current version or edition:
C:\path\docgen-17.0.5.zip
error in opening zip file

Windows also cannot open the zip file.
I'm using MagicDraw 17.0.5 with SysML, Camio Business Modeler booth installed and up.  Is there something I'm doing wrong?

**Comment by borromeotlhs** [comment]
I don't know if mdk is compatible with your version, try using anything from https://bintray.com/openmbee

Those might work
