### ISSUE TITLE
MDK will not build

### ISSUE THREAD

**Issue by gpgreen** [Open-MBEE/mdk#9]
The build.xml file contains these reference's that don't exist on a vanilla Magic Draw installation:
   1 import file="md.install.dir/data/eclipse/zip.xml"
   2 property name="md.build.tools.dir" location="md.install.dir/data/eclipse/resource/SMDP-PackageB"
   3 import file="md.build.tools.dir/build.md.plugin.xml"

**Comment by dlamoris** [comment]
fixed missing build-nojenkins.xml on 2.1, use that one instead of build.xml

**Comment by gpgreen** [comment]
Made some minor changes to the build to get it to work in our environment. See pull request #16
